In [1]:
import numpy as np 
import pandas as pd 

In [2]:
x = np.array(
    [[7,1],
    [1, 8],
    [2, 0],
    [9, 6]])
from sklearn.preprocessing import add_dummy_feature
x_new = add_dummy_feature(x)
print(x_new)

[[1. 7. 1.]
 [1. 1. 8.]
 [1. 2. 0.]
 [1. 9. 6.]]


In [3]:
from sklearn.preprocessing import FunctionTransformer